// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
    export interface GlobalComponents {
        ElButton: typeof import('element-plus/es')['ElButton']
        ElContainer: typeof import('element-plus/es')['ElContainer']
        ElDialog: typeof import('element-plus/es')['ElDialog']
        ElForm: typeof import('element-plus/es')['ElForm']
        ElFormItem: typeof import('element-plus/es')['ElFormItem']
        ElHeader: typeof import('element-plus/es')['ElHeader']
        ElIcon: typeof import('element-plus/es')['ElIcon']
        ElImage: typeof import('element-plus/es')['ElImage']
        ElInput: typeof import('element-plus/es')['ElInput']
        ElMain: typeof import('element-plus/es')['ElMain']
        ElMenu: typeof import('element-plus/es')['ElMenu']
        ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
        ElOption: typeof import('element-plus/es')['ElOption']
        ElPagination: typeof import('element-plus/es')['ElPagination']
        ElSelect: typeof import('element-plus/es')['ElSelect']
        ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
        ElTable: typeof import('element-plus/es')['ElTable']
        ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
        ElUpload: typeof import('element-plus/es')['ElUpload']
    }
}

export {}
